apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: admin-panel-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  - host: messaging-agent.globalnetservices.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ma-admin-panel
            port:
              number: 8081
