---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ma-synapse
  labels:
    app: ma-synapse
spec:
  serviceName: "synapse"
  replicas: 1
  selector:
    matchLabels:
      app: ma-synapse
  template:
    metadata:
      labels:
        app: ma-synapse
    spec:
      containers:
      - name: synapse
        image: matrixdotorg/synapse:latest
        command:
          - /bin/bash
          - -c
          - |
            if [ ! -f /data/homeserver.yaml ]; then
              /start.py generate
            fi
            exec /start.py
        env:
        - name: SYNAPSE_SERVER_NAME
          value: "synapse"
        - name: SYNAPSE_REPORT_STATS
          value: "no"
        - name: SYNAPSE_CONFIG_DIR
          value: "/data"
        - name: SYNAPSE_CONFIG_PATH
          value: "/data/homeserver.yaml"
        ports:
        - containerPort: 8008
          name: synapse
        volumeMounts:
        - name: synapse-data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: synapse-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 50Gi
---
apiVersion: v1
kind: Service
metadata:
  name: synapse
spec:
  ports:
    - port: 8008
  selector:
    app: ma-synapse
